### ISSUE TITLE
why only use RIGHT hand data?

### ISSUE THREAD

**Issue by markson14** [dahiyaaneesh/peclr#11]
This is a fantastic work, thank you for your contribution.
I have a question about why only use RIGHT hand data? I haven't found any clues from the paper. This is the code snippets I found in peclr/src/data_loader/youtube_loader.py
![image](https://user-images.githubusercontent.com/30102000/163600675-94cabda3-970c-41b9-b270-215701e33005.png)
If I want to add another dataset, shall I flip them to RIGHT hand(or LEFT hand)?

**Comment by spurra** [comment]
I think the original motivation was that since FH only contains right hands, we only focused on right hand images. It just makes it a little easier for the model to learn. If I recall correctly from past experiments (not PeCLR), in practice this gives only a minor boost. If you want to add another dataset, the question of flipping will depend on if you want to support right and left hand keypoint prediction or only one.

**Comment by markson14** [comment]
Thank you for your comment. That's a clear response.
